In [3]:
import pandas as pd 

df = pd.read_csv(r"C:\Users\lokes\Downloads\archive (4)\Sample - Superstore.csv",encoding='1252')

In [4]:
df.shape

(9994, 21)

In [6]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='str')

In [7]:
df.dtypes

Row ID             int64
Order ID             str
Order Date           str
Ship Date            str
Ship Mode            str
Customer ID          str
Customer Name        str
Segment              str
Country              str
City                 str
State                str
Postal Code        int64
Region               str
Product ID           str
Category             str
Sub-Category         str
Product Name         str
Sales            float64
Quantity           int64
Discount         float64
Profit           float64
dtype: object

In [10]:

df.duplicated().sum()

np.int64(0)

In [12]:
df.describe()

,Row ID,Postal Code,Sales,Quantity,Discount,Profit
count,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,55190.379428,229.858001,3.789574,0.156203,28.656896
std,2885.163629,32063.693350,623.245101,2.225110,0.206452,234.260108
min,1.000000,1040.000000,0.444000,1.000000,0.000000,-6599.978000
25%,2499.250000,23223.000000,17.280000,2.000000,0.000000,1.728750
50%,4997.500000,56430.500000,54.490000,3.000000,0.200000,8.666500
75%,7495.750000,90008.000000,209.940000,5.000000,0.200000,29.364000
max,9994.000000,99301.000000,22638.480000,14.000000,0.800000,8399.976000

In [13]:
#Total number of rows and columns.
df.shape

(9994, 21)

In [14]:
#Total sales across all orders.
df['Sales'].sum()

np.float64(2297200.8603)

In [15]:
#Total profit across all orders.
df['Profit'].sum()

np.float64(286397.0217)

In [17]:
#Number of unique product categories.
df['Category'].nunique()

3

In [19]:
Find the total sales for each Category.
df.groupby('Category')['Sales'].sum()

Category
Technology         836154.0330
Furniture          741999.7953
Office Supplies    719047.0320
Name: Sales, dtype: float64

In [25]:
#Find the total profit for each Category.
df.groupby('Category')['Profit'].sum()

Category
Furniture           18451.2728
Office Supplies    122490.8008
Technology         145454.9481
Name: Profit, dtype: float64

In [26]:
#Find both total sales and total profit for each Category in a single DataFrame.
df.groupby('Category')[['Sales', 'Profit']].sum()

                       Sales       Profit
Category
Furniture        741999.7953   18451.2728
Office Supplies  719047.0320  122490.8008
Technology       836154.0330  145454.9481

In [30]:
#Find the average sales and average profit for each Category.
df.groupby('Category').agg({'Sales':'mean', 'Profit':'mean'})

                      Sales     Profit
Category
Furniture        349.834887   8.699327
Office Supplies  119.324101  20.327050
Technology       452.709276  78.752002

In [31]:
#Find each category's total sales and rank the categories from highest to lowest sales.
df.groupby('Category')['Sales'].sum().rank(method='dense', ascending=False)

Category
Furniture          2.0
Office Supplies    3.0
Technology         1.0
Name: Sales, dtype: float64

In [37]:
#Find each category's total sales and rank the categories from highest to lowest sales.
Category_Avg_Profit = df.groupby('Category')['Sales'].sum()
Category_Avg_Profit = Category_Avg_Profit.sort_values(ascending=False)
Category_rank = Category_Avg_Profit.rank(method='dense', ascending=False)
print(Category_rank)

Category
Technology         1.0
Furniture          2.0
Office Supplies    3.0
Name: Sales, dtype: float64

In [41]:
df.drop(columns='Category_Avg_Profit')

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,1/21/2014,1/23/2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,9991,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,9992,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,9993,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,9994,CA-2017-119914,5/4/2017,5/9/2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

In [42]:

import pandas as pd

orders = pd.DataFrame({
    'Order_ID': [101, 102, 103, 104, 105],
    'Customer_ID': [1, 2, 1, 3, 4],
    'Sales': [500, 800, 300, 900, 400]
})

customers = pd.DataFrame({
    'Customer_ID': [1, 2, 3, 5],
    'Customer_Name': ['Ravi', 'Priya', 'Amit', 'Sneha'],
    'City': ['Hyderabad', 'Bengaluru', 'Chennai', 'Mumbai']
})

In [55]:
#Merge orders and customers to display customer names and cities alongside each order. Keep only matching customer IDs.
df = pd.merge(orders, customers, on='Customer_ID', how='inner')
df[['Customer_Name','City']]

  Customer_Name       City
0          Ravi  Hyderabad
1         Priya  Bengaluru
2          Ravi  Hyderabad
3          Amit    Chennai

In [ ]:
#Perform a left merge so that every order remains in the output, even if its customer details don't exist.

In [58]:
df = pd.merge(orders, customers, on='Customer_ID', how='left')
df[['Order_ID', 'Customer_ID', 'Sales', 'Customer_Name', 'City']]

   Order_ID  Customer_ID  Sales Customer_Name       City
0       101            1    500          Ravi  Hyderabad
1       102            2    800         Priya  Bengaluru
2       103            1    300          Ravi  Hyderabad
3       104            3    900          Amit    Chennai
4       105            4    400           NaN        NaN

In [ ]:
#Identify the order with a missing customer name.
df = pd.merge(
    orders, customers,
    on='Customer_ID',
    how='left'
)

missing_customers = df[df['Customer_Name'].isna()]

print(missing_customers)

   Order_ID  Customer_ID  Sales Customer_Name City
4       105            4    400           NaN  NaN

In [67]:
jan = pd.DataFrame({
    'Product': ['Laptop', 'Mouse'],
    'Sales': [50000, 1000]
})

feb = pd.DataFrame({
    'Product': ['Keyboard', 'Monitor'],
    'Sales': [2000, 15000]
})
pd.concat([jan, feb],ignore_index=True)

    Product  Sales
0    Laptop  50000
1     Mouse   1000
2  Keyboard   2000
3   Monitor  15000

In [69]:
#Combine them into a single DataFrame containing Employee_ID, Name, and Salary, matching employees by Employee_ID.
df1 = pd.DataFrame({
    'Employee_ID': [101, 102],
    'Name': ['Ravi', 'Priya']
})

df2 = pd.DataFrame({
    'Employee_ID': [101, 102],
    'Salary': [40000, 50000]
})

df = pd.merge(df1, df2, on='Employee_ID')
df

   Employee_ID   Name  Salary
0          101   Ravi   40000
1          102  Priya   50000

In [ ]:
df = pd.read_csv(r"C:\Users\lokes\Downloads\archive (4)\Sample - Superstore.csv",encoding='1252')
pd.pivot_table

TypeError: pivot_table() missing 1 required positional argument: 'data'