In [11]:
import pandas as pd

df = pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []

In [14]:
#list dataframe using list
import pandas as pd

data = ['lokesh','arvind','kranthi']
df = pd.DataFrame(data)
print(df)

         0
0   lokesh
1   arvind
2  kranthi

In [15]:
#list dataframe using dictionaries
import pandas as pd

data = {'name':['lokesh'],
        'age':[21],
        'gender':['male']}
df = pd.DataFrame(data)
print(df)

     name  age gender
0  lokesh   21   male

In [19]:
import pandas as pd

data = {'Name': ['Jake', 'Eve', 'Charlie','joe'],
        'Age': [ 22, 35, 28, 21],
        'Gender': [ 'Male', 'Female', 'Male', 'male'],
        'Salary': [40000, 70000, 48000, 40000]}
df = pd.DataFrame(data)
print(df.index)

RangeIndex(start=0, stop=4, step=1)

In [21]:
import pandas as pd

data = {'Name': ['Jake', 'Mike'],
        'Age': [25, 30],
        'Salary': [50000, 55000]}
df = pd.DataFrame(data)
# res = df.set_index('Name')
# print(res)
df

   Name  Age  Salary
0  Jake   25   50000
1  Mike   30   55000

In [22]:
res = df.set_index('Name')
res

      Age  Salary
Name
Jake   25   50000
Mike   30   55000

In [23]:
df.index

RangeIndex(start=0, stop=2, step=1)

In [24]:
res.index

Index(['Jake', 'Mike'], dtype='str', name='Name')

In [28]:
res[res.index=='Jake']

      Age  Salary
Name
Jake   25   50000

In [30]:
res[[False, True]]

      Age  Salary
Name
Mike   30   55000

In [43]:
import pandas as pd

data = {'Name': ['John', 'Alice', 'Bob', 'Eve', 'Charlie'], 
        'Age': [25, 30, 22, 35, 28], 
        'Gender': ['Male', 'Female', 'Male', 'Female', 'Male'], 
        'Salary': [50000, 55000, 40000, 70000, 48000]}

df = pd.DataFrame(data)
# Display the entire DataFrame
print(df)

      Name  Age  Gender  Salary
0     John   25    Male   50000
1    Alice   30  Female   55000
2      Bob   22    Male   40000
3      Eve   35  Female   70000
4  Charlie   28    Male   48000

In [47]:
column = df[['Name','Gender']]
print(column)

      Name  Gender
0     John    Male
1    Alice  Female
2      Bob    Male
3      Eve  Female
4  Charlie    Male

In [ ]:
row = df.iloc[0:4:2]
print(row)

   Name  Age Gender  Salary
0  John   25   Male   50000
2   Bob   22   Male   40000

In [60]:
rows_columns = df.iloc[0:3, 0:2]
rows_columns

    Name  Age
0   John   25
1  Alice   30
2    Bob   22

In [64]:
age_limit = df[(df['Age']>25) & (df['Salary']>40000) & (df['Gender']=='Female')]
age_limit

    Name  Age  Gender  Salary
1  Alice   30  Female   55000
3    Eve   35  Female   70000

In [65]:
index = df.at[3, 'Name']
index

'Eve'

In [66]:
df

      Name  Age  Gender  Salary
0     John   25    Male   50000
1    Alice   30  Female   55000
2      Bob   22    Male   40000
3      Eve   35  Female   70000
4  Charlie   28    Male   48000

In [68]:
df2 = df.set_index("Name").copy()

In [69]:
df2

         Age  Gender  Salary
Name
John      25    Male   50000
Alice     30  Female   55000
Bob       22    Male   40000
Eve       35  Female   70000
Charlie   28    Male   48000

In [74]:
df2.loc["John", ["Age", "Salary"]]

Age          25
Salary    50000
Name: John, dtype: int64

In [76]:
df2.iloc[0, [0,2]]

Age          25
Salary    50000
Name: John, dtype: int64

In [88]:
data = pd.read_csv(r"C:\Users\lokes\Downloads\archive\house_prices.csv")
data.head(5)

,Index,Title,Description,Amount(in rupees),Price (in rupees),location,Carpet Area,Status,Floor,Transaction,...,facing,overlooking,Society,Bathroom,Balcony,Car Parking,Ownership,Super Area,Dimensions,Plot Area
0,0,1 BHK Ready to Occupy Flat for sale in Srushti...,"Bhiwandi, Thane has an attractive 1 BHK Flat f...",42 Lac,6000.0,thane,500 sqft,Ready to Move,10 out of 11,Resale,...,NaN,NaN,Srushti Siddhi Mangal Murti Complex,1,2,NaN,NaN,NaN,NaN,NaN
1,1,2 BHK Ready to Occupy Flat for sale in Dosti V...,One can find this stunning 2 BHK flat for sale...,98 Lac,13799.0,thane,473 sqft,Ready to Move,3 out of 22,Resale,...,East,Garden/Park,Dosti Vihar,2,NaN,1 Open,Freehold,NaN,NaN,NaN
2,2,2 BHK Ready to Occupy Flat for sale in Sunrise...,Up for immediate sale is a 2 BHK apartment in ...,1.40 Cr,17500.0,thane,779 sqft,Ready to Move,10 out of 29,Resale,...,East,Garden/Park,Sunrise by Kalpataru,2,NaN,1 Covered,Freehold,NaN,NaN,NaN
3,3,1 BHK Ready to Occupy Flat for sale Kasheli,This beautiful 1 BHK Flat is available for sal...,25 Lac,NaN,thane,530 sqft,Ready to Move,1 out of 3,Resale,...,NaN,NaN,NaN,1,1,NaN,NaN,NaN,NaN,NaN
4,4,2 BHK Ready to Occupy Flat for sale in TenX Ha...,"This lovely 2 BHK Flat in Pokhran Road, Thane ...",1.60 Cr,18824.0,thane,635 sqft,Ready to Move,20 out of 42,Resale,...,West,"Garden/Park, Main Road",TenX Habitat Raymond Realty,2,NaN,1 Covered,Co-operative Society,NaN,NaN,NaN

In [89]:
data.columns

Index(['Index', 'Title', 'Description', 'Amount(in rupees)',
       'Price (in rupees)', 'location', 'Carpet Area', 'Status', 'Floor',
       'Transaction', 'Furnishing', 'facing', 'overlooking', 'Society',
       'Bathroom', 'Balcony', 'Car Parking', 'Ownership', 'Super Area',
       'Dimensions', 'Plot Area'],
      dtype='str')

In [93]:
data.dtypes

Index                  int64
Title                    str
Description              str
Amount(in rupees)        str
Price (in rupees)    float64
location                 str
Carpet Area              str
Status                   str
Floor                    str
Transaction              str
Furnishing               str
facing                   str
overlooking              str
Society                  str
Bathroom                 str
Balcony                  str
Car Parking              str
Ownership                str
Super Area               str
Dimensions           float64
Plot Area            float64
dtype: object

In [96]:
filtered_data = data[pd.to_numeric(data['Bathroom'], errors='coerce') > 2]
filtered_data

,Index,Title,Description,Amount(in rupees),Price (in rupees),location,Carpet Area,Status,Floor,Transaction,...,facing,overlooking,Society,Bathroom,Balcony,Car Parking,Ownership,Super Area,Dimensions,Plot Area
9,9,3 BHK Ready to Occupy Flat for sale in Pride P...,One can find this stunning 3 BHK flat for sale...,1.60 Cr,11150.0,thane,900 sqft,Ready to Move,3 out of 27,Resale,...,East,Garden/Park,Pride Palms,3,1,1 Covered,Freehold,NaN,NaN,NaN
13,13,4 BHK Ready to Occupy Flat for sale Hiranandan...,Creatively planned and constructed is a 4 BHK ...,4.25 Cr,17526.0,thane,1820 sqft,Ready to Move,18 out of 27,Resale,...,East,Garden/Park,NaN,4,1,2 Covered,Freehold,NaN,NaN,NaN
28,28,3 BHK Ready to Occupy Flat for sale in Palacia...,3 BHK flat available for sale in Thane in the ...,1.75 Cr,14344.0,thane,925 sqft,Ready to Move,8 out of 20,Resale,...,East,Garden/Park,Palacia Kingston Phase 2,3,3,1 Covered,Freehold,NaN,NaN,NaN
30,30,4 BHK Ready to Occupy Flat for sale in Hiranan...,"This lovely 4 BHK Flat in Manpada Thane West, ...",3.20 Cr,17827.0,thane,1350 sqft,Ready to Move,16 out of 27,Resale,...,East,Garden/Park,Hiranandani Meadows,3,1,2 Covered,Freehold,NaN,NaN,NaN
33,33,3 BHK Ready to Occupy Flat for sale in Rustomj...,This exquisite 3 BHK Flat is offered for sale ...,1.42 Cr,11008.0,thane,849 sqft,Ready to Move,1 out of 27,Resale,...,East,"Garden/Park, Main Road",Rustomjee Athena,3,NaN,1 Covered,Freehold,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187525,187525,3 BHK Ready to Occupy Flat for sale in Peer Mu...,Have a look at this immaculate 3 BHK flat for ...,44.9 Lac,3904.0,zirakpur,1050 sqft,Ready to Move,1 out of 3,New Property,...,North - East,"Garden/Park, Main Road",Peer Muchalla Apartments RWF,3,2,NaN,Freehold,NaN,NaN,NaN
187526,187526,3 BHK Ready to Occupy Flat for sale in Bollywo...,This magnificent 3 BHK Flat is available for s...,63 Lac,3225.0,zirakpur,NaN,Ready to Move,2 out of 4,New Property,...,East,Garden/Park,Bollywood Esencia,3,3,1 Covered,Freehold,1953 sqft,NaN,NaN
187527,187527,3 BHK Ready to Occupy Flat for sale in Sushma ...,Have a look at this immaculate 3 BHK flat for ...,55 Lac,3274.0,zirakpur,NaN,Ready to Move,4 out of 6,Resale,...,North - East,"Garden/Park, Main Road",Sushma Urban Views,3,NaN,1 Covered,NaN,1680 sqft,NaN,NaN
187528,187528,3 BHK Ready to Occupy Flat for sale in Bollywo...,"Gazipur, Zirakpur has an appealing 3 BHK flat ...",76 Lac,4343.0,zirakpur,1250 sqft,Ready to Move,1 out of 3,Resale,...,East,"Garden/Park, Main Road",Bollywood Esencia,3,2,"1 Covered,",Freehold,NaN,NaN,NaN
187530,187530,3 BHK Ready to Occupy Flat for sale in Affinit...,This exquisite 3 BHK Flat is offered for sale ...,1.18 Cr,6162.0,zirakpur,NaN,Ready to Move,5 out of 13,Resale,...,North - East,"Garden/Park, Pool",Affinity Greens,4,4,1 Covered,Freehold,1915 sqft,NaN,NaN

In [99]:
data = pd.read_csv(r"C:\Users\lokes\Downloads\student_performance_dataset.csv")
data

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,parental_education,internet_access,extracurricular_activities,part_time_job,previous_grade,final_exam_score,final_grade
0,1,Male,4.0,98.0,6.5,Bachelors,Yes,Yes,No,76.9,100.0,A
1,2,Female,6.3,100.0,5.7,High School,Yes,Yes,Yes,75.5,100.0,A
2,3,Male,4.9,85.3,7.9,Bachelors,Yes,No,Yes,88.5,97.3,A
3,4,Male,2.6,77.5,8.0,NaN,Yes,Yes,No,85.1,83.8,B
4,5,Male,2.2,89.6,4.6,Bachelors,Yes,No,Yes,61.8,68.3,D
...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Male,2.8,75.4,8.2,Masters,Yes,Yes,No,60.5,70.7,C
996,997,Male,6.7,88.4,7.1,NaN,No,Yes,No,82.2,99.5,A
997,998,Female,2.6,84.5,8.0,High School,Yes,Yes,Yes,65.2,79.2,C
998,999,Female,4.6,85.3,8.1,High School,No,No,Yes,52.2,82.2,B
999,1000,Male,3.9,77.4,6.1,Masters,Yes,No,No,45.4,70.4,C

In [100]:
data.columns

Index(['student_id', 'gender', 'study_time_hours', 'attendance_percent',
       'sleep_hours', 'parental_education', 'internet_access',
       'extracurricular_activities', 'part_time_job', 'previous_grade',
       'final_exam_score', 'final_grade'],
      dtype='str')

In [101]:
data.dtypes

student_id                      int64
gender                            str
study_time_hours              float64
attendance_percent            float64
sleep_hours                   float64
parental_education                str
internet_access                   str
extracurricular_activities        str
part_time_job                     str
previous_grade                float64
final_exam_score              float64
final_grade                       str
dtype: object

In [102]:
data.describe

<bound method NDFrame.describe of      student_id  gender  study_time_hours  attendance_percent  sleep_hours  \
0             1    Male               4.0                98.0          6.5
1             2  Female               6.3               100.0          5.7
2             3    Male               4.9                85.3          7.9
3             4    Male               2.6                77.5          8.0
4             5    Male               2.2                89.6          4.6
..          ...     ...               ...                 ...          ...
995         996    Male               2.8                75.4          8.2
996         997    Male               6.7                88.4          7.1
997         998  Female               2.6                84.5          8.0
998         999  Female               4.6                85.3          8.1
999        1000    Male               3.9                77.4          6.1

    parental_education internet_access extracurricular_activities  \
0            Bachelors             Yes                        Yes
1          High School             Yes                        Yes
2            Bachelors             Yes                         No
3                  NaN             Yes                        Yes
4            Bachelors             Yes                         No
..                 ...             ...                        ...
995            Masters             Yes                        Yes
996                NaN              No                        Yes
997        High School             Yes                        Yes
998        High School              No                         No
999            Masters             Yes                         No

    part_time_job  previous_grade  final_exam_score final_grade
0              No            76.9             100.0           A
1             Yes            75.5             100.0           A
2             Yes            88.5              97.3           A
3              No            85.1              83.8           B
4             Yes            61.8              68.3           D
..            ...             ...               ...         ...
995            No            60.5              70.7           C
996            No            82.2              99.5           A
997           Yes            65.2              79.2           C
998           Yes            52.2              82.2           B
999            No            45.4              70.4           C

[1000 rows x 12 columns]>

In [ ]:
check = data[['student_id'],'parental_education']
print(check.head(5))

KeyError: ('student_id', 'parental_education')